name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

env:
  GO_VERSION: '1.18'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos:
          - windows
          - linux
          - darwin
        goarch:
          - amd64
          - '386'
          - arm
          - arm64
    steps:
      - uses: actions/setup-go@v3
        if: ${{ !(matrix.goos == 'darwin' && (matrix.goarch == '386' || matrix.goarch == 'arm')) }}
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
        if: ${{ !(matrix.goos == 'darwin' && (matrix.goarch == '386' || matrix.goarch == 'arm')) }}
      - run: go mod download
        if: ${{ !(matrix.goos == 'darwin' && (matrix.goarch == '386' || matrix.goarch == 'arm')) }}
      - run: go build -v .
        if: ${{ !(matrix.goos == 'darwin' && (matrix.goarch == '386' || matrix.goarch == 'arm')) }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: go generate ./...
      - run: |
          git diff --compact-summary --exit-code || (echo; echo "Unexpected diff after code generation. Run 'go generate./...' and commit."; exit 1)

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - '1.3.*'
        mssql:
          - '2019-latest'
          - 'azure-sql'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go test --timeout 60m -v -cover ./internal/...
        env:
          TF_ACC: "1"
          TF_MSSQL_IMG_TAG: ${{ matrix.mssql }}
          TF_AZURE_SUBSCRIPTION_ID: ed349b81-e2df-40e0-ade4-9fc864f5a743
          TF_AZURE_RESOURCE_GROUP: terraform-mssql-tests
          AZURE_CLIENT_ID: 139df37c-3e72-4283-80c1-7be62f3d8e64
          AZURE_TENANT_ID: 7029fc72-c85c-4ecd-86f6-1ab9852b576f
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}